### ISSUE TITLE
MySQL8 cannot create table users - error rank

### ISSUE THREAD

**Issue by gigamaster** [xoopscube/xcl#152]

**Comment by kimura363** [comment]
Hi. Thank you for your powerful contributions.

This #152 has no description provided.
But I have tried a little.

In the 1st-step installation of XCL, creating a database table <prefix>_users fails.

It says:
ERROR 1064 (42000): You have an error in your SQL syntax: check the manual that corresponds to your MySQL server version for the right syntax to user near 'rank smallint(5) unsigned NOT NULL default '0',   level tinyint(3) unsigned NOT ' at line 20

Because the column name identifier "rank" is a reserved word of MySQL 8.0.2 or later.
So we have to specify the word "rank" as back-quoted as "`rank`" for the SQL statements in XCL files.
(INSERT and UPDATE SQL statements: Both [*.sql] files and [*.php] files.)
    - html/install/sql/mysql.structure.sql (554)
    - html/install/sql/upgrade/mysql.structure.sql (49)
    - html/kernel/user.php (600, 602)

Then, retrying XCL installation from the beginning, the CREATE TABLE statement for <prefix>_users fails again.

This time, it says:
ERROR 1071 (42000): Specified key was too long: max key length is 1000 bytes

Because,
(1) The maximum key size is 1000 bytes for the "MyISAM" storage engine of MySQL.
(2) Each characters has 4 bytes in case of MySQL8's default character set  "utf8mb4".
(3) So, 3 index KEYs of <prefix>_users table is too long: email, uidname, unamepass.

There are index definitions such as following, in the CREATE TABLE statement of <prefix>_users (See the file 'html/install/sql/mysql.structure.sql'):
`, KEY email (email),  KEY uidname (uid,uname), KEY unamepass (uname,pass) `

To fix those errors, there may be 3 ways:
(1)Remove too long KEYs. ( - It sounds not so good.)
(2)Change storage engine specifying "ENGINE=InnoDB" instead of "ENGINE=MyISAM"[or "ENGINE=MYISAM"]. ( - It sounds good.)
(3)Change character set with "ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci". ( - It will be conservative way.)

If you take the conservative way(3), for the safe change, check whole files under 'html' directory as like as `find html -not -type d -exec grep -i MyISAM {} \;`
Then for each files which has "myisam", copy the file (${F}) and replace the including phrase ("MyISAM" or "MYISAM") with the new phrase (MyISAM DEFAULT CHASET=utf8 COLLATE=utf8_general_ci) as like as:
`(mv ${F} ${F}._back_; cat ${F}._back_ | sed 's;M[yY]ISAM;MyISAM DEFAULT CHASET=utf8 COLLATE=utf8_general_ci;' > ${F}`.

(Sorry, but I cannot pull-request with a concrete fix.)

**Comment by gigamaster** [comment]
Hi, 
Thank you for your detailed description and the possible directions to solve this issue.
I'm back from Japan and that's great to get some help with bugs that require further updates.
Cheers, All the best ^_^/
